name = "Middle-earth: Refabricated"
author = "ViolaFlower Modding & Permdog99"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "993bcea27509aad4b713fc06ffdd6a6b06585ed03536fc30cceb2a8c33282956"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
